# Generated by Django 4.2.5 on 2023-09-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="consent_choice",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
