# Generated by Django 4.2.6 on 2023-10-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_can_be_contacted_user_can_data_be_shared"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(),
        ),
    ]
